# ------------------------------------------------------------
# Azure Functions
# ------------------------------------------------------------
quarkus.azure-functions.app-name=az-func-feedback-report
quarkus.azure-functions.runtime.java-version=25

# ------------------------------------------------------------
# Key Vault
# ------------------------------------------------------------
%dev.app.reports.storage.connection-string=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
%dev.app.reports.storage.container-name=feedback-reports

# Database
quarkus.datasource.db-kind=${FEEDBACK_DB_KIND:postgresql}
quarkus.datasource.jdbc.url=${kv//FeedbackDBUrl}
quarkus.datasource.username=${kv//FeedbackDBUser}
quarkus.datasource.password=${kv//FeedbackDBPassword}

%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=${FEEDBACK_DB_URL:jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
%dev.quarkus.datasource.username=${FEEDBACK_DB_USER:sa}
%dev.quarkus.datasource.password=${FEEDBACK_DB_PASSWORD:sa}

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa

# key vault
quarkus.azure.keyvault.secret.endpoint=${QUARKUS_AZURE_KEYVAULT_SECRET_ENDPOINT:}

# ------------------------------------------------------------
# Observability / Metrics
# ------------------------------------------------------------
feedback.metrics.prefix=feedback.report.

# Em cloud, a estrutura esperada deve existir previamente.
quarkus.hibernate-orm.schema-management.strategy=validate

# ------------------------------------------------------------
# Report Storage - Cloud / Production
# ------------------------------------------------------------
app.reports.storage.connection-string=${kv//FeedbackReportStorageConnectionString}
app.reports.storage.container-name=${kv//FeedbackReportContainerName:feedback-reports}

#%dev.app.reports.storage.connection-string=${FEEDBACK_REPORT_STORAGE_CONNECTION_STRING}
#%dev.app.reports.storage.container-name=${FEEDBACK_REPORT_CONTAINER_NAME}

# ------------------------------------------------------------
# Observability / Metrics
# ------------------------------------------------------------
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true

# Utiliza o exportador CDI da Azure (evitando o exportador OTLP local)
quarkus.otel.traces.exporter=cdi
quarkus.otel.metrics.exporter=cdi
quarkus.otel.logs.exporter=cdi
